#!/bin/bash

#SBATCH -n 72
#SBATCH -N 1
#SBATCH --mem=200G
#SBATCH --partition=long
#SBATCH --time=21-00:00:00
#SBATCH --job-name="ALIGN"
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/90daydata/maizegdb/sagnik/ABRIDGE/abridge_analysis_for_MS/STAR_alignments.output
#SBATCH --error=/90daydata/maizegdb/sagnik/ABRIDGE/abridge_analysis_for_MS/STAR_alignments.error

conda activate abridge
STAR_INDEX = "/90daydata/maizegdb/sagnik/data/HOMSA/genome/star_index_without_transcriptome" # Change accordingly
OUTPUT_DIR_ALIGNMENTS = "/90daydata/maizegdb/sagnik/ABRIDGE/abridge_analysis_for_MS/STAR_alignments" # Change accordingly
CPU = 72 # Change accordingly

align_reads_using_STAR.py \
--metadata ListOfNCBI-SRASamplesForExperimentST.csv \
--output_directory $OUTPUT_DIR_ALIGNMENTS \
--star_genome_index $STAR_INDEX \
--cpu $CPU \
--num_times 10 \
--input_location $OUTPUT_DIR_RAW_DATA \
1> $OUTPUT_DIR.output \
2> $OUTPUT_DIR.error 