#!/bin/bash

#SBATCH -n 1
#SBATCH -N 1
#SBATCH --mem=75G
#SBATCH --partition=atlas
#SBATCH --time=14-00:00:00
#SBATCH --job-name="ABRIDGE_ANALYSIS_MS"
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS.output
#SBATCH --error=/project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS.error
#SBATCH -A maizegdb

conda activate abridge

CPU=1 # Change accordingly
OUT_DIR="/project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS"
ln -s /project/maizegdb/sagnik/softwares/anaconda/bin/python python

abridge_reproduce_entire_analysis \
--metadata /project/maizegdb/sagnik/ABRIDGE/Abridge_analysis_for_MS/ListOfNCBI-SRASamplesForExperimentST.csv \
--output_directory "$OUT_DIR" \
--genome /project/maizegdb/sagnik/data/ARATH/genome/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa \
--cpu $CPU \
--num_times 5 \
--error_directory /project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS/errors \
1> "$OUT_DIR".output\
2> "$OUT_DIR".error