#!/bin/bash

#SBATCH -n 72
#SBATCH -N 1
#SBATCH --mem=100G
##SBATCH --partition=priority-mem768
##SBATCH --qos=maizegdb
#SBATCH --partition=medium
#SBATCH --time=7-00:00:00
#SBATCH --job-name="DOWNLOAD"
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/90daydata/maizegdb/sagnik/ABRIDGE/abridge_analysis_for_MS/raw_data.output
#SBATCH --error=/90daydata/maizegdb/sagnik/ABRIDGE/abridge_analysis_for_MS/raw_data.error

conda activate abridge

OUTPUT_DIR_RAW_DATA="/90daydata/maizegdb/sagnik/ABRIDGE/abridge_analysis_for_MS/raw_data" # Change accordingly
CPU=72 # Change accordingly

downloadAndDumpFastqFromSRA.py \
--cpu $CPU \
--sra download_these_SRA_samples \
--output $OUTPUT_DIR_RAW_DATA \
1> $OUTPUT_DIR.output \
2> $OUTPUT_DIR.error