#!/bin/bash

#SBATCH -n 80
#SBATCH -N 1
##SBATCH --partition=short
#SBATCH --partition=priority-mem768 -
#SBATCH -qos=maizegdb
#SBATCH --mem=150G
#SBATCH --time=2-00:00:00
#SBATCH --job-name="AA"
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS.output
#SBATCH --error=/project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS.error

conda activate abridge_pypy
module load samtools
module load libssh

python extensively_test_abridge.py