#!/bin/bash

#SBATCH -n 72
#SBATCH -N 1
#SBATCH --partition=long
#SBATCH --mem=200G
#SBATCH --qos=maizegdb
#SBATCH --time=21-00:00:00
#SBATCH --job-name="ABRIDGE_ANALYSIS_MS"
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS.output
#SBATCH --error=/project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS.error

conda activate abridge_pypy
module load samtools
module load libssh

CPU=72 # Change accordingly

abridge_reproduce_entire_analysis \
--metadata /project/maizegdb/sagnik/ABRIDGE/Abridge_analysis_for_MS/ListOfNCBI-SRASamplesForExperimentST.csv \
--output_directory /project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS \
--genome /project/maizegdb/sagnik/data/ARATH/genome/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa \
--cpu $CPU \
--num_times 1 \
--error_directory /project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS/errors \
--temp_directory /90daydata/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS/ \
1> /project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS.output \
2> /project/maizegdb/sagnik/ABRIDGE/data_analysis_for_MS.error